[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
solc_version = "0.8.29"
evm_version = 'shanghai'

remappings = ['foundry-huff/=lib/foundry-huff/src',"@openzeppelin/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
